TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_rotational_vel: .2
  min_in_place_rotational_vel: 0.1
  escape_vel: -0.05
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: false

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  
  goal_distance_bias: 0.1
  path_distance_bias: 0.1
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true
  
  oscillation_reset_dist: 0.05

